version: '3'
services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: simplicittask
    ports:
      - 8080:5173
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true